# Generated by Django 3.2.6 on 2021-08-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('GuideToExile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildguide',
            name='creation_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='buildguide',
            name='modification_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
