# Generated by Django 3.2.6 on 2021-08-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('GuideToExile', '0002_auto_20210827_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitch_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='youtube_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
