# Generated by Django 3.2.6 on 2021-08-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('GuideToExile', '0004_auto_20210827_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
