# Generated by Django 3.2.6 on 2021-08-31 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('GuideToExile', '0007_remove_userprofile_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildguide',
            old_name='build_id',
            new_name='guide_id',
        ),
        migrations.CreateModel(
            name='GuideComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('creation_datetime', models.DateTimeField()),
                ('modification_datetime', models.DateTimeField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                             to='GuideToExile.userprofile')),
                (
                'guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuideToExile.buildguide')),
            ],
        ),
    ]
