# Generated by Django 3.2.6 on 2021-09-03 16:17

from django.db import migrations


def load_asc_classes(apps, schema_editor):
    AscendancyClass = apps.get_model('GuideToExile', 'AscendancyClass')
    ascendancy_classes = [
        AscendancyClass(name='Juggernaut', base_class_name='Marauder'),
        AscendancyClass(name='Berserker', base_class_name='Marauder'),
        AscendancyClass(name='Chieftain', base_class_name='Marauder'),
        AscendancyClass(name='None', base_class_name='Marauder'),
        AscendancyClass(name='Deadeye', base_class_name='Ranger'),
        AscendancyClass(name='Raider', base_class_name='Ranger'),
        AscendancyClass(name='Pathfinder', base_class_name='Ranger'),
        AscendancyClass(name='None', base_class_name='Ranger'),
        AscendancyClass(name='Necromancer', base_class_name='Witch'),
        AscendancyClass(name='Elementalist', base_class_name='Witch'),
        AscendancyClass(name='Occultist', base_class_name='Witch'),
        AscendancyClass(name='None', base_class_name='Witch'),
        AscendancyClass(name='Slayer', base_class_name='Duelist'),
        AscendancyClass(name='Gladiator', base_class_name='Duelist'),
        AscendancyClass(name='Champion', base_class_name='Duelist'),
        AscendancyClass(name='None', base_class_name='Duelist'),
        AscendancyClass(name='Inquisitor', base_class_name='Templar'),
        AscendancyClass(name='Hierophant', base_class_name='Templar'),
        AscendancyClass(name='Guardian', base_class_name='Templar'),
        AscendancyClass(name='None', base_class_name='Templar'),
        AscendancyClass(name='Assassin', base_class_name='Shadow'),
        AscendancyClass(name='Saboteur', base_class_name='Shadow'),
        AscendancyClass(name='Trickster', base_class_name='Shadow'),
        AscendancyClass(name='None', base_class_name='Shadow'),
        AscendancyClass(name='Ascendant', base_class_name='Scion'),
        AscendancyClass(name='None', base_class_name='Scion'),
    ]
    for asc_class in ascendancy_classes:
        asc_class.save()


def delete_asc_classes(apps, schema_editor):
    AscendancyClass = apps.get_model('GuideToExile', 'AscendancyClass')
    AscendancyClass.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('GuideToExile', '0010_ascendancyclass'),
    ]

    operations = [
        migrations.RunPython(load_asc_classes, delete_asc_classes),
    ]
