# Generated by Django 3.2.6 on 2021-09-03 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('GuideToExile', '0011_auto_20210903_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildguide',
            name='ascendancy_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='GuideToExile.ascendancyclass'),
        ),
    ]
