# Generated by Django 3.2.6 on 2021-09-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('GuideToExile', '0013_auto_20210903_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='ascendancyclass',
            name='_base_class_name',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'Marauder'), (2, 'Ranger'), (3, 'Witch'), (4, 'Duelist'), (5, 'Templar'), (6, 'Shadow'),
                         (7, 'Scion')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ascendancyclass',
            name='_name',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'Juggernaut'), (2, 'Berserker'), (3, 'Chieftain'), (4, 'Deadeye'), (5, 'Raider'),
                         (6, 'Pathfinder'), (7, 'Necromancer'), (8, 'Elementalist'), (9, 'Occultist'), (10, 'Slayer'),
                         (11, 'Gladiator'), (12, 'Champion'), (13, 'Inquisitor'), (14, 'Hierophant'), (15, 'Guardian'),
                         (16, 'Assassin'), (17, 'Saboteur'), (18, 'Trickster'), (19, 'Ascendant'), (20, 'None')],
                default=1),
            preserve_default=False,
        ),
    ]
