# Generated by Django 3.2.6 on 2021-09-03 17:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('GuideToExile', '0015_auto_20210903_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ascendancyclass',
            name='base_class_name',
        ),
        migrations.RemoveField(
            model_name='ascendancyclass',
            name='name',
        ),
    ]
