# Generated by Django 3.2.6 on 2021-09-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('GuideToExile', '0017_auto_20210903_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='buildguide',
            name='primary_active_skills',
            field=models.ManyToManyField(to='GuideToExile.ActiveSkill'),
        ),
    ]
