# Generated by Django 3.2.6 on 2021-09-08 10:06
import json

from django.contrib.staticfiles import finders
from django.db import migrations

from GuideToExile.settings import GEMS_FILE


def load_active_skills(apps, schema_editor):
    ActiveSkill = apps.get_model('GuideToExile', 'ActiveSkill')
    gems_file = finders.find(GEMS_FILE)
    active_skill_names = []
    with open(gems_file, 'r', encoding='utf-8') as file:
        data = json.load(file)
        for key, details in data.items():
            if 'active_skill' in details:
                active_skill_names.append(details['active_skill']['display_name'])
            elif 'base_item' in details and details['base_item'] is not None:
                active_skill_names.append(details['base_item']['display_name'])

    active_skill_names = list(set(active_skill_names))
    active_skill_names.sort()
    for name in active_skill_names:
        if 'support' not in name.lower():
            active_skill = ActiveSkill(name=name)
            active_skill.save()


def delete_active_skills(apps, schema_editor):
    ActiveSkill = apps.get_model('GuideToExile', 'ActiveSkill')
    ActiveSkill.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('GuideToExile', '0018_auto_20210908_1205'),
    ]

    operations = [
        migrations.RunPython(load_active_skills, delete_active_skills),
    ]
