# Generated by Django 3.2.6 on 2021-09-08 10:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('GuideToExile', '0019_auto_20210908_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildguide',
            old_name='primary_active_skills',
            new_name='primary_skills',
        ),
    ]
