# Generated by Django 3.2.6 on 2021-09-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('GuideToExile', '0020_rename_primary_active_skills_buildguide_primary_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildguide',
            name='slug',
            field=models.SlugField(max_length=180),
        ),
        migrations.AlterField(
            model_name='buildguide',
            name='title',
            field=models.CharField(max_length=180),
        ),
    ]
