# Generated by Django 3.2.6 on 2021-09-13 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('GuideToExile', '0021_auto_20210911_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildguide',
            name='draft',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='public_version', to='GuideToExile.buildguide'),
        ),
        migrations.AddField(
            model_name='buildguide',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buildguide',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
