# Generated by Django 3.2.6 on 2021-09-13 16:22

from django.db import migrations


def make_existing_guides_published(apps, schema_editor):
    BuildGuide = apps.get_model('GuideToExile', 'BuildGuide')
    for guide in BuildGuide.objects.all():
        guide.is_published = True
        guide.save()


def revert_make_existing_guides_published(apps, schema_editor):
    BuildGuide = apps.get_model('GuideToExile', 'BuildGuide')
    for guide in BuildGuide.objects.all():
        guide.is_published = False
        guide.save()


class Migration(migrations.Migration):
    dependencies = [
        ('GuideToExile', '0022_auto_20210913_1819'),
    ]

    operations = [
        migrations.RunPython(make_existing_guides_published, revert_make_existing_guides_published)
    ]
