# Generated by Django 3.2.6 on 2021-09-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('GuideToExile', '0024_auto_20210913_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildguide',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'draft'), (2, 'public'), (3, 'archived')]),
        ),
    ]
