# Generated by Django 3.2.6 on 2021-09-21 15:41

from django.db import migrations, models

import GuideToExile.json_encoder


class Migration(migrations.Migration):
    dependencies = [
        ('GuideToExile', '0026_auto_20210921_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildguide',
            name='pob_details',
            field=models.JSONField(decoder=GuideToExile.json_encoder.BuildDetailsJsonDecoder,
                                   encoder=GuideToExile.json_encoder.BuildDetailsJsonEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='buildguide',
            name='pob_string',
            field=models.CharField(max_length=40000, null=True),
        ),
    ]
