# Generated by Django 3.2.6 on 2021-09-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('GuideToExile', '0030_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildguide',
            name='pob_string',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='buildguide',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
