# Generated by Django 3.2.6 on 2021-09-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('GuideToExile', '0031_auto_20210928_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildguide',
            name='video_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
