# Generated by Django 3.2.5 on 2021-07-30 10:15

import BuildsOfExile.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keystone',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueItem',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BuildGuide',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('pob_string', models.CharField(max_length=40000)),
                ('pob_details', djongo.models.fields.EmbeddedField(model_container=BuildsOfExile.models.PobDetails)),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=40000)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('keystones', models.ManyToManyField(related_name='keystones_related_builds', to='BuildsOfExile.Keystone')),
                ('unique_items', models.ManyToManyField(related_name='unique_items_related_builds', to='BuildsOfExile.Keystone')),
            ],
        ),
    ]
