# Generated by Django 3.1.13 on 2021-07-30 15:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('BuildsOfExile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildguide',
            old_name='_id',
            new_name='build_id',
        ),
    ]
