# Generated by Django 3.1.13 on 2021-07-30 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('BuildsOfExile', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildguide',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='BuildsOfExile.userprofile'),
        ),
    ]
